# Generated by Django 5.1.3 on 2024-11-10 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coverage_type",
            fields=[
                ("coverage_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("bodily_injury_liability", "Bodily Injury Liability"),
                            (
                                "personal_injury_protection",
                                "Personal Injury Protection",
                            ),
                            ("property_damage_liability", "Property Damage Liability"),
                            ("collision", "Collision"),
                            ("comprehensive", "Comprehensive"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=6
                    ),
                ),
                (
                    "income_group",
                    models.CharField(
                        choices=[
                            ("0-25K", "0- $25K"),
                            ("25-70K", "$25-$70K"),
                            ("70K+", ">$70K"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("North", "North"),
                            ("South", "South"),
                            ("East", "East"),
                            ("West", "West"),
                        ],
                        max_length=5,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Date",
            fields=[
                ("date_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                ("quarter", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("policy_id", models.IntegerField()),
                ("premium", models.IntegerField()),
                (
                    "vehicle_segment",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C")], max_length=1
                    ),
                ),
                ("bodily_injury_liability", models.BooleanField(default=True)),
                ("personal_injury_protection", models.BooleanField(default=True)),
                ("property_damage_liability", models.BooleanField(default=True)),
                ("collision", models.BooleanField(default=True)),
                ("comprehensive", models.BooleanField(default=True)),
                (
                    "customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policies",
                        to="analysis.customer",
                    ),
                ),
                (
                    "date_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policies",
                        to="analysis.date",
                    ),
                ),
            ],
        ),
    ]
