# Generated by Django 5.1.3 on 2024-11-10 20:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0002_populate_coverage_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="date",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="date",
            name="month",
            field=models.IntegerField(default=11),
        ),
        migrations.AlterField(
            model_name="date",
            name="quarter",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="date",
            name="year",
            field=models.IntegerField(default=2024),
        ),
    ]
