# Generated by Django 5.1.3 on 2024-11-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "analysis",
            "0003_alter_date_date_alter_date_month_alter_date_quarter_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="bodily_injury_liability",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="policy",
            name="collision",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="policy",
            name="comprehensive",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="policy",
            name="personal_injury_protection",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="policy",
            name="property_damage_liability",
            field=models.BooleanField(default=False),
        ),
    ]
